### PR TITLE
Support signed integers for `bswap` intrinsic

### PR DESCRIPTION
**Pull request by LegNeato**
Fixes https://github.com/Rust-GPU/rust-gpu/issues/169

### CODE REVIEW

**Comment by LegNeato** [comment]
Not sure where we add runtime tests?

**Comment by LegNeato** [comment]
@FractalFir No rush, but I would love it if you can confirm this fixes the issue you saw. If you are busy, no worries!

**Comment by FractalFir** [comment]
It *seems* to work fine, and fix the original issue. There is a *very slim* chance I missed something, but it should be OK.

**Comment by LegNeato** [comment]
Well, even if it is wrong it is better than a panic I guess. Thanks for testing!

**Pull request merged**
